export class Store {
  public id: number;
  public publicId: string;
  public enviromentId: number;
  public websiteId: number;
  public name: string;
  public email: string;
  public appTitle: string;
  public faviconLink: string;
  public homeTemplate: string;
  public logoSrc: string;
  public logoWidth: string;
  public logoHeight: string;
  public stylePath: string;
  public fontsLink: string;
  public storeUrl: string;
  public url: string;
  public painelUrl: string;
  public status: number;
  public allowRegister: boolean;
  public paymentTime: number;
  public paymentTrigger: number;
  public minimumValue: number;
  public protectedRegister: boolean;
  public comissionType: number;
  public comissionValue: number;
  public createdAt: string;
  public updatedAt: string;
}
